In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Messy_Dataset.csv")
df.head()

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,OrderDate,PaymentMethod,City,DeliveryStatus,ReturnFlag
0,O1001,C01,Phone,Electronics,1.0,50000.0,2023-01-10,Credit Card,Karachi,Delivered,0
1,O1002,C02,Laptop,Electronics,NaN,120000.0,2023-02-15,Cash,Islamabad,Delivered,0
2,O1003,C03,Headphones,Electronics,2.0,NaN,2023-03-12,Card,Lahore,Returned,1
3,O1004,C04,Shirt,Fashion,3.0,2000.0,2023-01-25,Cash,NaN,Delivered,0
4,O1005,C05,Shoes,Fashion,1.0,5000.0,2023-02-10,Card,Karachi,Delivered,NaN

In [4]:
df.isnull().sum()

OrderID           0
CustomerID        0
Product           0
Category          0
Quantity          4
UnitPrice         4
OrderDate         0
PaymentMethod     0
City              4
DeliveryStatus    0
ReturnFlag        4
dtype: int64

In [5]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())
df["UnitPrice"] = df["UnitPrice"].fillna(df["UnitPrice"].median())
df["City"] = df["City"].fillna("Unknown")
df["ReturnFlag"] = df["ReturnFlag"].fillna(0)
df

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,OrderDate,PaymentMethod,City,DeliveryStatus,ReturnFlag
0,O1001,C01,Phone,Electronics,1.0,50000.0,2023-01-10,Credit Card,Karachi,Delivered,0
1,O1002,C02,Laptop,Electronics,1.0,120000.0,2023-02-15,Cash,Islamabad,Delivered,0
2,O1003,C03,Headphones,Electronics,2.0,15000.0,2023-03-12,Card,Lahore,Returned,1
3,O1004,C04,Shirt,Fashion,3.0,2000.0,2023-01-25,Cash,Unknown,Delivered,0
4,O1005,C05,Shoes,Fashion,1.0,5000.0,2023-02-10,Card,Karachi,Delivered,0
...,...,...,...,...,...,...,...,...,...,...,...
785,O2196,C1195,Tablet,Electronics,1.0,81500.0,2026-09-10,Credit Card,Lahore,Delivered,0
786,O2197,C1196,Phone,Electronics,1.0,51000.0,2026-09-11,Cash,Karachi,Delivered,0
787,O2198,C1197,Laptop,Electronics,1.0,120000.0,2026-09-12,Card,Lahore,Delivered,0
788,O2199,C1198,Headphones,Electronics,2.0,3800.0,2026-09-13,Cash,Islamabad,Returned,1
789,O2200,C1199,Shirt,Fashion,4.0,2100.0,2026-09-14,Card,Karachi,Delivered,0

In [6]:
df.duplicated().sum()

70

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

# Feature Engineering

In [9]:
df['TotalRevenue'] = df['Quantity'] * df['UnitPrice']
df.head()

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,OrderDate,PaymentMethod,City,DeliveryStatus,ReturnFlag,TotalRevenue
0,O1001,C01,Phone,Electronics,1.0,50000.0,2023-01-10,Credit Card,Karachi,Delivered,0,50000.0
1,O1002,C02,Laptop,Electronics,1.0,120000.0,2023-02-15,Cash,Islamabad,Delivered,0,120000.0
2,O1003,C03,Headphones,Electronics,2.0,15000.0,2023-03-12,Card,Lahore,Returned,1,30000.0
3,O1004,C04,Shirt,Fashion,3.0,2000.0,2023-01-25,Cash,Unknown,Delivered,0,6000.0
4,O1005,C05,Shoes,Fashion,1.0,5000.0,2023-02-10,Card,Karachi,Delivered,0,5000.0

In [10]:
df['HighOrder'] = np.where(df["TotalRevenue"] > 50000,1,0)
df.head()

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,OrderDate,PaymentMethod,City,DeliveryStatus,ReturnFlag,TotalRevenue,HighOrder
0,O1001,C01,Phone,Electronics,1.0,50000.0,2023-01-10,Credit Card,Karachi,Delivered,0,50000.0,0
1,O1002,C02,Laptop,Electronics,1.0,120000.0,2023-02-15,Cash,Islamabad,Delivered,0,120000.0,1
2,O1003,C03,Headphones,Electronics,2.0,15000.0,2023-03-12,Card,Lahore,Returned,1,30000.0,0
3,O1004,C04,Shirt,Fashion,3.0,2000.0,2023-01-25,Cash,Unknown,Delivered,0,6000.0,0
4,O1005,C05,Shoes,Fashion,1.0,5000.0,2023-02-10,Card,Karachi,Delivered,0,5000.0,0

In [11]:
df["City"].value_counts()

Karachi      304
Lahore       272
Islamabad    141
Unknown        3
Name: City, dtype: int64

In [12]:
df["CityGroup"] = df["City"].map({
    "Karachi":"Tier1",
    "Lahore":"Tier2",
    "Islamabad":"Tier2",
    "Unknown":"Tier3"
})
df

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,OrderDate,PaymentMethod,City,DeliveryStatus,ReturnFlag,TotalRevenue,HighOrder,CityGroup
0,O1001,C01,Phone,Electronics,1.0,50000.0,2023-01-10,Credit Card,Karachi,Delivered,0,50000.0,0,Tier1
1,O1002,C02,Laptop,Electronics,1.0,120000.0,2023-02-15,Cash,Islamabad,Delivered,0,120000.0,1,Tier2
2,O1003,C03,Headphones,Electronics,2.0,15000.0,2023-03-12,Card,Lahore,Returned,1,30000.0,0,Tier2
3,O1004,C04,Shirt,Fashion,3.0,2000.0,2023-01-25,Cash,Unknown,Delivered,0,6000.0,0,Tier3
4,O1005,C05,Shoes,Fashion,1.0,5000.0,2023-02-10,Card,Karachi,Delivered,0,5000.0,0,Tier1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785,O2196,C1195,Tablet,Electronics,1.0,81500.0,2026-09-10,Credit Card,Lahore,Delivered,0,81500.0,1,Tier2
786,O2197,C1196,Phone,Electronics,1.0,51000.0,2026-09-11,Cash,Karachi,Delivered,0,51000.0,1,Tier1
787,O2198,C1197,Laptop,Electronics,1.0,120000.0,2026-09-12,Card,Lahore,Delivered,0,120000.0,1,Tier2
788,O2199,C1198,Headphones,Electronics,2.0,3800.0,2026-09-13,Cash,Islamabad,Returned,1,7600.0,0,Tier2
789,O2200,C1199,Shirt,Fashion,4.0,2100.0,2026-09-14,Card,Karachi,Delivered,0,8400.0,0,Tier1

# EDA (Exploratory Data Analysis)

In [13]:
df.groupby("Product")["TotalRevenue"].sum().sort_values(ascending=False)

Product
Laptop        12218500.0
Tablet         7887500.0
Phone          5066900.0
Watch          2578300.0
Headphones      834700.0
Shoes           827400.0
Shirt           817700.0
Name: TotalRevenue, dtype: float64

In [14]:
df.groupby("City")["TotalRevenue"].sum().sort_values(ascending=False)

City
Lahore       16272050.0
Karachi       9329150.0
Islamabad     4612300.0
Unknown         17500.0
Name: TotalRevenue, dtype: float64

In [15]:
df.groupby("City")["HighOrder"].sum().sort_values(ascending=False)

City
Lahore       148
Karachi       82
Islamabad     43
Unknown        0
Name: HighOrder, dtype: int32

In [16]:
df["ReturnFlag"].unique()

array(['0', '1', 0, '0s'], dtype=object)

In [17]:
df["ReturnFlag"] = pd.to_numeric(df["ReturnFlag"], errors="coerce")

In [18]:
df["ReturnFlag"].fillna(0, inplace=True)

In [19]:
print(round((df["ReturnFlag"].mean()*100),2), "%")

18.06 %

In [20]:
df.groupby("Category")["TotalRevenue"].mean()

Category
Electronics    65181.954887
Fashion        13157.009346
Name: TotalRevenue, dtype: float64

In [21]:
df["PaymentMethod"].value_counts()

Cash           309
Card           287
Credit Card    124
Name: PaymentMethod, dtype: int64

In [22]:
df.to_csv("CLeaned_Data.csv")