In [30]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv("Messy_dataset.csv")
df.head()

,CustomerID,Name,Age,City,JoinDate,LastPurchaseDate,TotalOrders,TotalSpent,AvgOrderValue,PaymentMethod
0,C01,Ali,25,Karachi,2021-01-10,2023-07-01,15,150000,10000,Card
1,C02,Sara,28,Lahore,2020-03-15,2023-06-20,20,300000,15000,Cash
2,C03,Usman,30,Islamabad,2019-07-22,2022-12-15,10,80000,8000,Card
3,C04,Ayesha,29,Karachi,2022-05-10,2023-07-10,8,60000,7500,Card
4,C05,Hassan,27,Lahore,2021-11-01,2023-05-05,12,120000,10000,Cash

In [32]:
df["JoinDate"] = pd.to_datetime(df["JoinDate"])
df["LastPurchaseDate"] = pd.to_datetime(df["LastPurchaseDate"])

# Feature Engineering

In [33]:
df["CustomerLifetime"] = (df["LastPurchaseDate"] - df["JoinDate"]).dt.days
df.head()

,CustomerID,Name,Age,City,JoinDate,LastPurchaseDate,TotalOrders,TotalSpent,AvgOrderValue,PaymentMethod,CustomerLifetime
0,C01,Ali,25,Karachi,2021-01-10,2023-07-01,15,150000,10000,Card,902
1,C02,Sara,28,Lahore,2020-03-15,2023-06-20,20,300000,15000,Cash,1192
2,C03,Usman,30,Islamabad,2019-07-22,2022-12-15,10,80000,8000,Card,1242
3,C04,Ayesha,29,Karachi,2022-05-10,2023-07-10,8,60000,7500,Card,426
4,C05,Hassan,27,Lahore,2021-11-01,2023-05-05,12,120000,10000,Cash,550

In [39]:
today = pd.to_datetime("2023-07-20")
df["Recency"] = (today - df["LastPurchaseDate"]).dt.days
df.head()

,CustomerID,Name,Age,City,JoinDate,LastPurchaseDate,TotalOrders,TotalSpent,AvgOrderValue,PaymentMethod,CustomerLifetime,Recency,PurchaseFrequency,MonetaryValue,CLV,CustomerSegment
0,C01,Ali,25,Karachi,2021-01-10,2023-07-01,15,150000,10000,Card,902,19.0,0.016630,10000.0,150000.0,Loyal
1,C02,Sara,28,Lahore,2020-03-15,2023-06-20,20,300000,15000,Cash,1192,30.0,0.016779,15000.0,300000.0,VIP
2,C03,Usman,30,Islamabad,2019-07-22,2022-12-15,10,80000,8000,Card,1242,217.0,0.008052,8000.0,80000.0,Regular
3,C04,Ayesha,29,Karachi,2022-05-10,2023-07-10,8,60000,7500,Card,426,10.0,0.018779,7500.0,60000.0,Regular
4,C05,Hassan,27,Lahore,2021-11-01,2023-05-05,12,120000,10000,Cash,550,76.0,0.021818,10000.0,120000.0,Loyal

In [40]:
df["PurchaseFrequency"] = df["TotalOrders"] / df["CustomerLifetime"]
df

,CustomerID,Name,Age,City,JoinDate,LastPurchaseDate,TotalOrders,TotalSpent,AvgOrderValue,PaymentMethod,CustomerLifetime,Recency,PurchaseFrequency,MonetaryValue,CLV,CustomerSegment
0,C01,Ali,25,Karachi,2021-01-10,2023-07-01,15,150000,10000,Card,902,19.0,0.016630,10000.000000,150000.0,Loyal
1,C02,Sara,28,Lahore,2020-03-15,2023-06-20,20,300000,15000,Cash,1192,30.0,0.016779,15000.000000,300000.0,VIP
2,C03,Usman,30,Islamabad,2019-07-22,2022-12-15,10,80000,8000,Card,1242,217.0,0.008052,8000.000000,80000.0,Regular
3,C04,Ayesha,29,Karachi,2022-05-10,2023-07-10,8,60000,7500,Card,426,10.0,0.018779,7500.000000,60000.0,Regular
4,C05,Hassan,27,Lahore,2021-11-01,2023-05-05,12,120000,10000,Cash,550,76.0,0.021818,10000.000000,120000.0,Loyal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1205,C1206,Khalid,28,Peshawar,2019-07-06,2019-11-19,20,995144,49757,Mobile Wallet,136,1339.0,0.147059,49757.200000,995144.0,VIP
1206,C1207,Farhan,42,Karachi,2019-08-15,2021-03-31,31,712949,22998,Cash,594,841.0,0.052189,22998.354839,712949.0,VIP
1207,C1208,Mahnoor,40,Multan,2018-01-15,2021-12-13,11,366367,33306,Bank Transfer,1428,584.0,0.007703,33306.090909,366367.0,VIP
1208,C1209,Waqar,20,Multan,2021-11-13,2023-02-01,27,651545,24131,Mobile Wallet,445,169.0,0.060674,24131.296296,651545.0,VIP
1209,C1210,Zain,24,Hyderabad,2021-03-31,2023-01-22,25,92255,3690,Bank Transfer,662,179.0,0.037764,3690.200000,92255.0,Regular

In [41]:
df["MonetaryValue"] = df["TotalSpent"] / df["TotalOrders"]
df.head()

,CustomerID,Name,Age,City,JoinDate,LastPurchaseDate,TotalOrders,TotalSpent,AvgOrderValue,PaymentMethod,CustomerLifetime,Recency,PurchaseFrequency,MonetaryValue,CLV,CustomerSegment
0,C01,Ali,25,Karachi,2021-01-10,2023-07-01,15,150000,10000,Card,902,19.0,0.016630,10000.0,150000.0,Loyal
1,C02,Sara,28,Lahore,2020-03-15,2023-06-20,20,300000,15000,Cash,1192,30.0,0.016779,15000.0,300000.0,VIP
2,C03,Usman,30,Islamabad,2019-07-22,2022-12-15,10,80000,8000,Card,1242,217.0,0.008052,8000.0,80000.0,Regular
3,C04,Ayesha,29,Karachi,2022-05-10,2023-07-10,8,60000,7500,Card,426,10.0,0.018779,7500.0,60000.0,Regular
4,C05,Hassan,27,Lahore,2021-11-01,2023-05-05,12,120000,10000,Cash,550,76.0,0.021818,10000.0,120000.0,Loyal

In [42]:
df["CLV"] = df["PurchaseFrequency"] * df["MonetaryValue"] * df["CustomerLifetime"]
df.head()

,CustomerID,Name,Age,City,JoinDate,LastPurchaseDate,TotalOrders,TotalSpent,AvgOrderValue,PaymentMethod,CustomerLifetime,Recency,PurchaseFrequency,MonetaryValue,CLV,CustomerSegment
0,C01,Ali,25,Karachi,2021-01-10,2023-07-01,15,150000,10000,Card,902,19.0,0.016630,10000.0,150000.0,Loyal
1,C02,Sara,28,Lahore,2020-03-15,2023-06-20,20,300000,15000,Cash,1192,30.0,0.016779,15000.0,300000.0,VIP
2,C03,Usman,30,Islamabad,2019-07-22,2022-12-15,10,80000,8000,Card,1242,217.0,0.008052,8000.0,80000.0,Regular
3,C04,Ayesha,29,Karachi,2022-05-10,2023-07-10,8,60000,7500,Card,426,10.0,0.018779,7500.0,60000.0,Regular
4,C05,Hassan,27,Lahore,2021-11-01,2023-05-05,12,120000,10000,Cash,550,76.0,0.021818,10000.0,120000.0,Loyal

In [43]:
df["CustomerSegment"] = np.where(df["CLV"] > 200000, "VIP",
                         np.where(df["CLV"] > 100000, "Loyal", "Regular"))
df.head()

,CustomerID,Name,Age,City,JoinDate,LastPurchaseDate,TotalOrders,TotalSpent,AvgOrderValue,PaymentMethod,CustomerLifetime,Recency,PurchaseFrequency,MonetaryValue,CLV,CustomerSegment
0,C01,Ali,25,Karachi,2021-01-10,2023-07-01,15,150000,10000,Card,902,19.0,0.016630,10000.0,150000.0,Loyal
1,C02,Sara,28,Lahore,2020-03-15,2023-06-20,20,300000,15000,Cash,1192,30.0,0.016779,15000.0,300000.0,VIP
2,C03,Usman,30,Islamabad,2019-07-22,2022-12-15,10,80000,8000,Card,1242,217.0,0.008052,8000.0,80000.0,Regular
3,C04,Ayesha,29,Karachi,2022-05-10,2023-07-10,8,60000,7500,Card,426,10.0,0.018779,7500.0,60000.0,Regular
4,C05,Hassan,27,Lahore,2021-11-01,2023-05-05,12,120000,10000,Cash,550,76.0,0.021818,10000.0,120000.0,Loyal

# EDA (Exploratory Data Analysis)

In [44]:
df.sort_values(by="CLV", ascending=False)

,CustomerID,Name,Age,City,JoinDate,LastPurchaseDate,TotalOrders,TotalSpent,AvgOrderValue,PaymentMethod,CustomerLifetime,Recency,PurchaseFrequency,MonetaryValue,CLV,CustomerSegment
816,C817,Farhan,24,Quetta,2018-10-27,2022-11-19,37,998524,26987,Mobile Wallet,1484,243.0,0.024933,26987.135135,998524.0,VIP
1113,C1114,Anum,36,Sialkot,2019-09-12,2022-10-05,22,998444,45384,Cash,1119,288.0,0.019660,45383.818182,998444.0,VIP
1024,C1025,Noman,21,Gujranwala,2023-06-01,2024-12-25,19,998231,52538,Bank Transfer,573,NaN,0.033159,52538.473684,998231.0,VIP
817,C818,Ibrahim,33,Lahore,2018-12-15,2019-12-11,19,997282,52489,Card,361,1317.0,0.052632,52488.526316,997282.0,VIP
1169,C1170,Bushra,34,Multan,2021-11-28,2023-12-05,36,997005,27695,Card,737,NaN,0.048847,27694.583333,997005.0,VIP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,C352,Farhan,43,Quetta,2022-10-18,2023-12-31,3,24890,8297,Cash,439,NaN,0.006834,8296.666667,24890.0,Regular
1153,C1154,Tania,25,Faisalabad,2022-02-15,2023-05-29,30,24156,805,Card,468,52.0,0.064103,805.200000,24156.0,Regular
200,C201,Noman,43,Sialkot,2021-10-14,2023-06-13,5,23612,4722,Mobile Wallet,607,37.0,0.008237,4722.400000,23612.0,Regular
765,C766,Hina,20,Rawalpindi,2023-07-23,2024-12-31,37,21022,568,Bank Transfer,527,NaN,0.070209,568.162162,21022.0,Regular
173,C174,Arslan,42,Islamabad,2023-04-06,2023-07-02,3,18836,6279,Cash,87,18.0,0.034483,6278.666667,18836.0,Regular

In [48]:
df[df["Recency"] < 0]
df.loc[df["Recency"] < 0, "Recency"] = None
df["Recency"] = df["Recency"].clip(lower=0)
df.head()

,CustomerID,Name,Age,City,JoinDate,LastPurchaseDate,TotalOrders,TotalSpent,AvgOrderValue,PaymentMethod,CustomerLifetime,Recency,PurchaseFrequency,MonetaryValue,CLV,CustomerSegment
0,C01,Ali,25,Karachi,2021-01-10,2023-07-01,15,150000,10000,Card,902,19.0,0.016630,10000.0,150000.0,Loyal
1,C02,Sara,28,Lahore,2020-03-15,2023-06-20,20,300000,15000,Cash,1192,30.0,0.016779,15000.0,300000.0,VIP
2,C03,Usman,30,Islamabad,2019-07-22,2022-12-15,10,80000,8000,Card,1242,217.0,0.008052,8000.0,80000.0,Regular
3,C04,Ayesha,29,Karachi,2022-05-10,2023-07-10,8,60000,7500,Card,426,10.0,0.018779,7500.0,60000.0,Regular
4,C05,Hassan,27,Lahore,2021-11-01,2023-05-05,12,120000,10000,Cash,550,76.0,0.021818,10000.0,120000.0,Loyal

In [50]:
round(df.groupby("City")["CLV"].mean(), 2)

City
Faisalabad    413178.76
Gujranwala    414490.11
Hyderabad     394506.63
Islamabad     463165.80
Karachi       434521.80
Lahore        447264.79
Multan        406513.74
Peshawar      420650.44
Quetta        425650.02
Rawalpindi    418492.31
Sialkot       406568.29
Name: CLV, dtype: float64

In [52]:
df["CustomerSegment"].value_counts()

VIP        899
Loyal      179
Regular    132
Name: CustomerSegment, dtype: int64

In [53]:
df.groupby("PaymentMethod")["CLV"].mean()

PaymentMethod
Bank Transfer    441728.890966
Card             404070.905109
Cash             433537.911585
Mobile Wallet    405097.982578
Name: CLV, dtype: float64

In [57]:
df.sort_values(by="Recency")

,CustomerID,Name,Age,City,JoinDate,LastPurchaseDate,TotalOrders,TotalSpent,AvgOrderValue,PaymentMethod,CustomerLifetime,Recency,PurchaseFrequency,MonetaryValue,CLV,CustomerSegment,Recency_missing
159,C160,Anum,25,Multan,2022-03-08,2023-07-20,21,347375,16542,Mobile Wallet,499,0.0,0.042084,16541.666667,347375.0,VIP,0
36,C37,Khalid,29,Peshawar,2023-06-17,2023-07-19,15,200019,13335,Card,32,1.0,0.468750,13334.600000,200019.0,VIP,0
276,C277,Farhan,20,Peshawar,2021-09-22,2023-07-19,27,397157,14710,Bank Transfer,665,1.0,0.040602,14709.518519,397157.0,VIP,0
1198,C1199,Laiba,40,Islamabad,2023-04-21,2023-07-18,38,403165,10610,Bank Transfer,88,2.0,0.431818,10609.605263,403165.0,VIP,0
495,C496,Waqar,32,Lahore,2022-03-16,2023-07-18,4,64429,16107,Mobile Wallet,489,2.0,0.008180,16107.250000,64429.0,Regular,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,C686,Bilal,25,Sialkot,2021-05-31,2023-12-31,5,62248,12450,Mobile Wallet,944,1938.0,0.005297,12449.600000,62248.0,Regular,1
686,C687,Danish,22,Rawalpindi,2021-12-28,2023-12-31,35,235235,6721,Mobile Wallet,733,1938.0,0.047749,6721.000000,235235.0,VIP,1
687,C688,Khalid,20,Peshawar,2023-01-27,2023-12-31,38,480797,12653,Card,338,1938.0,0.112426,12652.552632,480797.0,VIP,1
678,C679,Ali,30,Karachi,2022-03-22,2023-12-31,9,105821,11758,Cash,649,1938.0,0.013867,11757.888889,105821.0,Loyal,1
604,C605,Ayesha,20,Sialkot,2021-01-24,2023-09-03,34,418034,12295,Bank Transfer,952,1938.0,0.035714,12295.117647,418034.0,VIP,1

In [55]:
df["Recency_missing"] = df["Recency"].isnull().astype(int)
df["Recency"] = df["Recency"].fillna(df["Recency"].max())

In [56]:
df

,CustomerID,Name,Age,City,JoinDate,LastPurchaseDate,TotalOrders,TotalSpent,AvgOrderValue,PaymentMethod,CustomerLifetime,Recency,PurchaseFrequency,MonetaryValue,CLV,CustomerSegment,Recency_missing
0,C01,Ali,25,Karachi,2021-01-10,2023-07-01,15,150000,10000,Card,902,19.0,0.016630,10000.000000,150000.0,Loyal,0
1,C02,Sara,28,Lahore,2020-03-15,2023-06-20,20,300000,15000,Cash,1192,30.0,0.016779,15000.000000,300000.0,VIP,0
2,C03,Usman,30,Islamabad,2019-07-22,2022-12-15,10,80000,8000,Card,1242,217.0,0.008052,8000.000000,80000.0,Regular,0
3,C04,Ayesha,29,Karachi,2022-05-10,2023-07-10,8,60000,7500,Card,426,10.0,0.018779,7500.000000,60000.0,Regular,0
4,C05,Hassan,27,Lahore,2021-11-01,2023-05-05,12,120000,10000,Cash,550,76.0,0.021818,10000.000000,120000.0,Loyal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1205,C1206,Khalid,28,Peshawar,2019-07-06,2019-11-19,20,995144,49757,Mobile Wallet,136,1339.0,0.147059,49757.200000,995144.0,VIP,0
1206,C1207,Farhan,42,Karachi,2019-08-15,2021-03-31,31,712949,22998,Cash,594,841.0,0.052189,22998.354839,712949.0,VIP,0
1207,C1208,Mahnoor,40,Multan,2018-01-15,2021-12-13,11,366367,33306,Bank Transfer,1428,584.0,0.007703,33306.090909,366367.0,VIP,0
1208,C1209,Waqar,20,Multan,2021-11-13,2023-02-01,27,651545,24131,Mobile Wallet,445,169.0,0.060674,24131.296296,651545.0,VIP,0
1209,C1210,Zain,24,Hyderabad,2021-03-31,2023-01-22,25,92255,3690,Bank Transfer,662,179.0,0.037764,3690.200000,92255.0,Regular,0

In [58]:
df.isnull().sum()

CustomerID           0
Name                 0
Age                  0
City                 0
JoinDate             0
LastPurchaseDate     0
TotalOrders          0
TotalSpent           0
AvgOrderValue        0
PaymentMethod        0
CustomerLifetime     0
Recency              0
PurchaseFrequency    0
MonetaryValue        0
CLV                  0
CustomerSegment      0
Recency_missing      0
dtype: int64

In [59]:
df.dr().sum()

c:\users\aik\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

CustomerID           C01C02C03C04C05C06C07C08C09C10C11C12C13C14C15C...
Name                 AliSaraUsmanAyeshaHassanZaraAhmedNoorImranHina...
Age                                                              39279
City                 KarachiLahoreIslamabadKarachiLahoreIslamabadKa...
TotalOrders                                                      26564
TotalSpent                                                   510973958
AvgOrderValue                                                 30418820
PaymentMethod        CardCashCardCardCashCardCardCashCardCashCardCa...
CustomerLifetime                                                667465
Recency                                                      1326336.0
PurchaseFrequency                                           137.903781
MonetaryValue                                          30418834.297304
CLV                                                        510973958.0
CustomerSegment      LoyalVIPRegularRegularLoyalVIPVIPRegularLoyalR...
Recency_missing                                                    393
dtype: object