In [1]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv("Dataset_messy.csv")
df.head()

,CustomerID,Name,Age,Gender,Country,Product,PurchaseAmount,Discount,PurchaseDate,Rating
0,201,Ali,25.0,Male,Pakistan,Phone,50000.0,5.0,2023-01-10,4.5
1,202,Sara,NaN,Female,India,Laptop,120000.0,10.0,2023-02-15,5.0
2,203,Usman,30.0,Male,Pakistan,Tablet,NaN,15.0,2023-03-12,4.0
3,204,Ayesha,29.0,Female,NaN,Phone,45000.0,5.0,2023-01-25,3.5
4,205,Hassan,27.0,Male,India,Laptop,110000.0,NaN,2023-02-10,4.8

In [20]:
df.shape

(999, 10)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      999 non-null    int64
 1   Name            999 non-null    object
 2   Age             986 non-null    float64
 3   Gender          999 non-null    object
 4   Country         998 non-null    object
 5   Product         999 non-null    object
 6   PurchaseAmount  963 non-null    float64
 7   Discount        940 non-null    float64
 8   PurchaseDate    999 non-null    object
 9   Rating          980 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 78.2+ KB

In [22]:
df.describe()

       CustomerID         Age  PurchaseAmount    Discount      Rating
count  999.000000  986.000000      963.000000  940.000000  980.000000
mean   437.687688   28.719067    91619.418484   10.401064    4.404694
std    143.318313    2.786330    29168.826575    4.347499    0.313598
min    201.000000   24.000000    45000.000000    5.000000    3.500000
25%    311.000000   27.000000    71000.000000    5.000000    4.100000
50%    436.000000   28.000000    84500.000000   10.000000    4.300000
75%    560.500000   31.000000   123000.000000   12.000000    4.700000
max    710.000000   35.000000   147000.000000   20.000000    5.000000

In [23]:
df.isnull().sum()

CustomerID         0
Name               0
Age               13
Gender             0
Country            1
Product            0
PurchaseAmount    36
Discount          59
PurchaseDate       0
Rating            19
dtype: int64

In [24]:
df.duplicated().sum()

0

In [25]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Country"] = df["Country"].fillna("Unknown")
df["PurchaseAmount"] = df["PurchaseAmount"].fillna(df["PurchaseAmount"].median())
df["Discount"] = df["Discount"].fillna(0)
df["Rating"] = df["Rating"].fillna(df["Rating"].mean())
df

,CustomerID,Name,Age,Gender,Country,Product,PurchaseAmount,Discount,PurchaseDate,Rating
0,201,Ali,25.0,Male,Pakistan,Phone,50000.0,5.0,2023-01-10,4.5
1,202,Sara,28.0,Female,India,Laptop,120000.0,10.0,2023-02-15,5.0
2,203,Usman,30.0,Male,Pakistan,Tablet,84500.0,15.0,2023-03-12,4.0
3,204,Ayesha,29.0,Female,Unknown,Phone,45000.0,5.0,2023-01-25,3.5
4,205,Hassan,27.0,Male,India,Laptop,110000.0,0.0,2023-02-10,4.8
...,...,...,...,...,...,...,...,...,...,...
994,245,Shahzaib,31.0,Male,India,Laptop,126000.0,10.0,2023-10-24,4.8
995,246,Areeba,27.0,Female,UK,Tablet,81000.0,0.0,2023-10-26,4.2
996,247,Hassan,34.0,Male,Pakistan,Phone,94000.0,20.0,2023-10-28,4.9
997,248,Nimra,26.0,Female,India,Laptop,117000.0,12.0,2023-10-30,4.6
998,249,Rehan,30.0,Male,UK,Tablet,87000.0,15.0,2023-11-01,4.4

In [26]:
df.isnull().sum()

CustomerID        0
Name              0
Age               0
Gender            0
Country           0
Product           0
PurchaseAmount    0
Discount          0
PurchaseDate      0
Rating            0
dtype: int64

In [28]:
df["PurchaseDate"] = pd.to_datetime(df["PurchaseDate"])
df

,CustomerID,Name,Age,Gender,Country,Product,PurchaseAmount,Discount,PurchaseDate,Rating
0,201,Ali,25.0,Male,Pakistan,Phone,50000.0,5.0,2023-01-10,4.5
1,202,Sara,28.0,Female,India,Laptop,120000.0,10.0,2023-02-15,5.0
2,203,Usman,30.0,Male,Pakistan,Tablet,84500.0,15.0,2023-03-12,4.0
3,204,Ayesha,29.0,Female,Unknown,Phone,45000.0,5.0,2023-01-25,3.5
4,205,Hassan,27.0,Male,India,Laptop,110000.0,0.0,2023-02-10,4.8
...,...,...,...,...,...,...,...,...,...,...
994,245,Shahzaib,31.0,Male,India,Laptop,126000.0,10.0,2023-10-24,4.8
995,246,Areeba,27.0,Female,UK,Tablet,81000.0,0.0,2023-10-26,4.2
996,247,Hassan,34.0,Male,Pakistan,Phone,94000.0,20.0,2023-10-28,4.9
997,248,Nimra,26.0,Female,India,Laptop,117000.0,12.0,2023-10-30,4.6
998,249,Rehan,30.0,Male,UK,Tablet,87000.0,15.0,2023-11-01,4.4

# Feature Engineering

In [29]:
df["NetPurchase"] = df["PurchaseAmount"] - (df["PurchaseAmount"]*df["Discount"] / 100)
df

,CustomerID,Name,Age,Gender,Country,Product,PurchaseAmount,Discount,PurchaseDate,Rating,NetPurchase
0,201,Ali,25.0,Male,Pakistan,Phone,50000.0,5.0,2023-01-10,4.5,47500.0
1,202,Sara,28.0,Female,India,Laptop,120000.0,10.0,2023-02-15,5.0,108000.0
2,203,Usman,30.0,Male,Pakistan,Tablet,84500.0,15.0,2023-03-12,4.0,71825.0
3,204,Ayesha,29.0,Female,Unknown,Phone,45000.0,5.0,2023-01-25,3.5,42750.0
4,205,Hassan,27.0,Male,India,Laptop,110000.0,0.0,2023-02-10,4.8,110000.0
...,...,...,...,...,...,...,...,...,...,...,...
994,245,Shahzaib,31.0,Male,India,Laptop,126000.0,10.0,2023-10-24,4.8,113400.0
995,246,Areeba,27.0,Female,UK,Tablet,81000.0,0.0,2023-10-26,4.2,81000.0
996,247,Hassan,34.0,Male,Pakistan,Phone,94000.0,20.0,2023-10-28,4.9,75200.0
997,248,Nimra,26.0,Female,India,Laptop,117000.0,12.0,2023-10-30,4.6,102960.0
998,249,Rehan,30.0,Male,UK,Tablet,87000.0,15.0,2023-11-01,4.4,73950.0

In [30]:
df["AgeGroup"] = np.where(df["Age"] < 30, "Young", "Adult")
df

,CustomerID,Name,Age,Gender,Country,Product,PurchaseAmount,Discount,PurchaseDate,Rating,NetPurchase,AgeGroup
0,201,Ali,25.0,Male,Pakistan,Phone,50000.0,5.0,2023-01-10,4.5,47500.0,Young
1,202,Sara,28.0,Female,India,Laptop,120000.0,10.0,2023-02-15,5.0,108000.0,Young
2,203,Usman,30.0,Male,Pakistan,Tablet,84500.0,15.0,2023-03-12,4.0,71825.0,Adult
3,204,Ayesha,29.0,Female,Unknown,Phone,45000.0,5.0,2023-01-25,3.5,42750.0,Young
4,205,Hassan,27.0,Male,India,Laptop,110000.0,0.0,2023-02-10,4.8,110000.0,Young
...,...,...,...,...,...,...,...,...,...,...,...,...
994,245,Shahzaib,31.0,Male,India,Laptop,126000.0,10.0,2023-10-24,4.8,113400.0,Adult
995,246,Areeba,27.0,Female,UK,Tablet,81000.0,0.0,2023-10-26,4.2,81000.0,Young
996,247,Hassan,34.0,Male,Pakistan,Phone,94000.0,20.0,2023-10-28,4.9,75200.0,Adult
997,248,Nimra,26.0,Female,India,Laptop,117000.0,12.0,2023-10-30,4.6,102960.0,Young
998,249,Rehan,30.0,Male,UK,Tablet,87000.0,15.0,2023-11-01,4.4,73950.0,Adult

In [31]:
df["CustomerScore"] = (df["NetPurchase"] / 10000) + df["Rating"]
df

,CustomerID,Name,Age,Gender,Country,Product,PurchaseAmount,Discount,PurchaseDate,Rating,NetPurchase,AgeGroup,CustomerScore
0,201,Ali,25.0,Male,Pakistan,Phone,50000.0,5.0,2023-01-10,4.5,47500.0,Young,9.2500
1,202,Sara,28.0,Female,India,Laptop,120000.0,10.0,2023-02-15,5.0,108000.0,Young,15.8000
2,203,Usman,30.0,Male,Pakistan,Tablet,84500.0,15.0,2023-03-12,4.0,71825.0,Adult,11.1825
3,204,Ayesha,29.0,Female,Unknown,Phone,45000.0,5.0,2023-01-25,3.5,42750.0,Young,7.7750
4,205,Hassan,27.0,Male,India,Laptop,110000.0,0.0,2023-02-10,4.8,110000.0,Young,15.8000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,245,Shahzaib,31.0,Male,India,Laptop,126000.0,10.0,2023-10-24,4.8,113400.0,Adult,16.1400
995,246,Areeba,27.0,Female,UK,Tablet,81000.0,0.0,2023-10-26,4.2,81000.0,Young,12.3000
996,247,Hassan,34.0,Male,Pakistan,Phone,94000.0,20.0,2023-10-28,4.9,75200.0,Adult,12.4200
997,248,Nimra,26.0,Female,India,Laptop,117000.0,12.0,2023-10-30,4.6,102960.0,Young,14.8960
998,249,Rehan,30.0,Male,UK,Tablet,87000.0,15.0,2023-11-01,4.4,73950.0,Adult,11.7950

# Exploratory Data Analysis

In [32]:
df.groupby("Country")["NetPurchase"].sum().sort_values(ascending=False)

Country
India       38239250.0
UK          23776105.0
Pakistan    19922400.0
Unknown        42750.0
Name: NetPurchase, dtype: float64

In [33]:
# BEST SELLING PRODUCT
df["Product"].value_counts()

Phone     335
Laptop    332
Tablet    332
Name: Product, dtype: int64

In [35]:
# Rating - Spending Relationship
df.groupby("Rating")["NetPurchase"].mean()

Rating
3.500000     42750.000000
3.800000     50540.000000
3.900000     52396.153846
4.000000     55898.026316
4.100000     66195.192308
4.200000     69490.409836
4.300000     63111.184211
4.400000     71840.277778
4.404694     90898.684211
4.500000     93161.363636
4.600000    110316.770833
4.700000    108477.865169
4.800000    106562.637363
4.900000    106880.467290
5.000000    107100.000000
Name: NetPurchase, dtype: float64

In [36]:
df["Discount"].mean()

9.786786786786786

In [37]:
df.to_csv("Cleaned_Dataset.csv")