In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Messy_dataset.csv")
df.head()

,TransactionID,UserID,Age,TransactionAmount,TransactionType,Location,DeviceType,AccountBalance,IsForeignTransaction,TimeOfDay,Fraud
0,T001,U01,25,5000,Online,Karachi,Mobile,20000,0,Night,0
1,T002,U02,30,200000,Online,London,Laptop,500000,1,Night,1
2,T003,U03,22,1500,POS,Karachi,Mobile,15000,0,Afternoon,0
3,T004,U04,45,300000,Online,Dubai,Laptop,1000000,1,Night,1
4,T005,U05,28,7000,POS,Karachi,Mobile,25000,0,Evening,0

In [3]:
df.isnull().sum()

TransactionID           0
UserID                  0
Age                     0
TransactionAmount       0
TransactionType         0
Location                0
DeviceType              0
AccountBalance          0
IsForeignTransaction    0
TimeOfDay               0
Fraud                   0
dtype: int64

In [4]:
df.duplicated().sum()

0

In [5]:
df["TransactionAmount"] = df["TransactionAmount"].astype(float)
df["AccountBalance"] = df["AccountBalance"].astype(float)

# Feature Engineering

In [7]:
df["HighValue"] = np.where(df["TransactionAmount"] > 100000, 1,0)
df

,TransactionID,UserID,Age,TransactionAmount,TransactionType,Location,DeviceType,AccountBalance,IsForeignTransaction,TimeOfDay,Fraud,HighValue
0,T001,U01,25,5000.0,Online,Karachi,Mobile,20000.0,0,Night,0,0
1,T002,U02,30,200000.0,Online,London,Laptop,500000.0,1,Night,1,1
2,T003,U03,22,1500.0,POS,Karachi,Mobile,15000.0,0,Afternoon,0,0
3,T004,U04,45,300000.0,Online,Dubai,Laptop,1000000.0,1,Night,1,1
4,T005,U05,28,7000.0,POS,Karachi,Mobile,25000.0,0,Evening,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
985,T296,U296,35,495000.0,Online,USA,Laptop,800000.0,1,Night,1,1
986,T297,U297,24,4000.0,POS,Karachi,Mobile,15000.0,0,Morning,0,0
987,T298,U298,37,300000.0,Online,UK,Laptop,660000.0,1,Night,1,1
988,T299,U299,29,7200.0,POS,Karachi,Mobile,22000.0,0,Afternoon,0,0
989,T300,U300,42,350000.0,Online,Dubai,Laptop,990000.0,1,Night,1,1

In [8]:
df["ForeignRisk"] = df["IsForeignTransaction"]

In [9]:
df

,TransactionID,UserID,Age,TransactionAmount,TransactionType,Location,DeviceType,AccountBalance,IsForeignTransaction,TimeOfDay,Fraud,HighValue,ForeignRisk
0,T001,U01,25,5000.0,Online,Karachi,Mobile,20000.0,0,Night,0,0,0
1,T002,U02,30,200000.0,Online,London,Laptop,500000.0,1,Night,1,1,1
2,T003,U03,22,1500.0,POS,Karachi,Mobile,15000.0,0,Afternoon,0,0,0
3,T004,U04,45,300000.0,Online,Dubai,Laptop,1000000.0,1,Night,1,1,1
4,T005,U05,28,7000.0,POS,Karachi,Mobile,25000.0,0,Evening,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,T296,U296,35,495000.0,Online,USA,Laptop,800000.0,1,Night,1,1,1
986,T297,U297,24,4000.0,POS,Karachi,Mobile,15000.0,0,Morning,0,0,0
987,T298,U298,37,300000.0,Online,UK,Laptop,660000.0,1,Night,1,1,1
988,T299,U299,29,7200.0,POS,Karachi,Mobile,22000.0,0,Afternoon,0,0,0
989,T300,U300,42,350000.0,Online,Dubai,Laptop,990000.0,1,Night,1,1,1

In [10]:
df["NightRisk"] = np.where(df["TimeOfDay"] == "Night", 1, 0)

In [11]:
df

,TransactionID,UserID,Age,TransactionAmount,TransactionType,Location,DeviceType,AccountBalance,IsForeignTransaction,TimeOfDay,Fraud,HighValue,ForeignRisk,NightRisk
0,T001,U01,25,5000.0,Online,Karachi,Mobile,20000.0,0,Night,0,0,0,1
1,T002,U02,30,200000.0,Online,London,Laptop,500000.0,1,Night,1,1,1,1
2,T003,U03,22,1500.0,POS,Karachi,Mobile,15000.0,0,Afternoon,0,0,0,0
3,T004,U04,45,300000.0,Online,Dubai,Laptop,1000000.0,1,Night,1,1,1,1
4,T005,U05,28,7000.0,POS,Karachi,Mobile,25000.0,0,Evening,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,T296,U296,35,495000.0,Online,USA,Laptop,800000.0,1,Night,1,1,1,1
986,T297,U297,24,4000.0,POS,Karachi,Mobile,15000.0,0,Morning,0,0,0,0
987,T298,U298,37,300000.0,Online,UK,Laptop,660000.0,1,Night,1,1,1,1
988,T299,U299,29,7200.0,POS,Karachi,Mobile,22000.0,0,Afternoon,0,0,0,0
989,T300,U300,42,350000.0,Online,Dubai,Laptop,990000.0,1,Night,1,1,1,1

# Exploratory Data Analysis (EDA)

In [12]:
df["Fraud"].value_counts()

0    495
1    495
Name: Fraud, dtype: int64

In [13]:
df.shape

(990, 14)

In [14]:
df.groupby("Fraud")["TransactionAmount"].mean()

Fraud
0      5954.747475
1    333616.161616
Name: TransactionAmount, dtype: float64

In [18]:
df.groupby("Location")["Fraud"].sum()

Location
Dubai        141
Islamabad      0
Karachi       16
Lahore         0
London        15
UK           165
USA          158
Name: Fraud, dtype: int64

In [19]:
df.groupby("TimeOfDay")["Fraud"].mean()

TimeOfDay
Afternoon    0.000000
Evening      0.000000
Morning      0.000000
Night        0.997984
Name: Fraud, dtype: float64

In [20]:
df.to_csv("Cleaned_CSV.csv")